### PR TITLE
Run optimisation on previous seasons

### PR DESCRIPTION
**Pull request by jack89roberts**
Successfully managed to run the squad generation then GW2 transfer optimisation for the 19/20 season with this. 

Notes:
- Should update test data to check this & prediction on previous seasons to make sure everything propagated correctly
- 20/21 season get errors due to duplicate Ben Davies (in prediction) - see #351 , but works for 19/20
- Should fill database with older seasons for this (e.g. if we usually use last 3 seasons of data,  we should have 3 seasons of data before the season we're optimising for)

### CODE REVIEW

**Comment by jack89roberts** [comment]
@nbarlowATI I got an optimisation on past seasons working earlier this week 🎉 . There wasn't much left to do actually, main thing is to simulate applying transfers (so this adds the suggested transfers from the first week in the strategy to the `Transaction` table, which e.g. means you can generate an initial squad and then run the transfer optimisation with that squad for the next gameweek)

I tested it with:

```
airsenal_run_prediction --season 1920 --gameweek_start 1 --gameweek_end 4
airsenal_make_squad --num_gw 1 --verbose --season 1920
airsenal_run_optimization --season 1920 --gw_start 2 --gw_end 3
```

**Comment by nbarlowATI** [comment]
Amazing!    Great work Jack!!!!   
I'll make an Issue where we can put down some of the things we might want to investigate by replaying previous seasons (e.g. looking 3 vs 5 weeks ahead, ... )

**Comment by jack89roberts** [comment]
I had an initial look at trying that - in the 20/21 season there are errors due to there being two Ben Davies, and in 19/20 errors during the Covid postponement (I think something fails if a gameweek has no fixtures), but it's not far off working for a whole season.

**Comment by jack89roberts** [comment]
To investigate: No recommended transfers if optimising with wildcard

**Comment by jack89roberts** [comment]
I found a lingering bug (which actually isn't related to this branch but caused the problem above) so I think this could be merged now, with any further improvements in a separate PR. Should add some test data for another season so we can check it properly, though.

**Pull request merged**
