### PR TITLE
Fix pre-wildcard or -free hit squad used for points calculation

### PR DESCRIPTION
**Pull request by jack89roberts**
I noticed that the optimisation wasn't recommending strategies including wildcard or free hit when `--allow_wildcard` or `--allow_free_hit` were passed as options.

I tracked this down to `make_best_transfers` in `optimization_utils`, where a `new_squad` variable is created for the resulting wildcard/free hit team but the expected points for the team are calculated using the old `squad` variable.

I've changed this so all strategies (not just wildcard/free hit) create a `new_squad` variable and points are always calculated on `new_squad`. `new_squad` is also returned in all cases except for free hit, where the original `squad` is returned instead as free hit transfers don't apply for following weeks.

@nbarlowATI could you double-check this makes sense? Especially the logic re returning the original squad for free hit - I'm not sure whether this is dealt with somewhere other than `make_best_transfers`, or whether returning the squad without the free hit transfers will break something elsewhere? Thanks 🙂

### CODE REVIEW

**Comment by nbarlowATI** [comment]
@jack89roberts  ah, well spotted!   
Definitely a good idea to always get `new_squad` - this was for sure a bug with the wildcard/free-hit points calculation in this function.
An I am 90% sure that returning `squad` for the free-hit is the right thing to do - the only place this will be used is as the starting point for the following week's optimization in `fill_transfersuggestion_table.optimize` - the actual squad that gets printed out after the optimization is made from `get_starting_squad` and then applying the transfers-in and transfers-out.

I will test this properly, but currently having gcc/pystan/bpl troubles - not sure if this is as a result of updating OSX or downgrading bpl or both :(

**Comment by jack89roberts** [comment]
Oh dear ☹️, did you update to Big Sur? I haven't upgraded and it's working normally for me with bpl 0.0.4, though I can't get it to work in python 3.8 on my laptop (only 3.7).

Just pushed a commit to remove `apply_strategy` from `optimization_utils`, which as far as I can tell isn't used any more for the tree optimisation.

**Comment by nbarlowATI** [comment]
Not Big Sur, but just Catalina... but then something didn't work so reinstalled xcode command-line tools, and now even more things are broken! :-/
Will try in docker...

**Review by nbarlowATI — APPROVED** [review]
Excellent, yes, I checked and this seems to be doing exactly what we want.   The free-hit and wildcard both work as expected.

**Pull request merged**
