### PR TITLE
Feature/314 choose chip week

### PR DESCRIPTION
**Pull request by nbarlowATI**
Modify command-line arguments to `airsenal_run_optimization` - now, rather than, e.g. `--allow_wildcard`, we have `--wildcard_week`, which can be -1 (default - don't play chip), 0 (equivalent to old `allow_x` - chip can be played any week), or gw (int, play this chip in gameweek gw).
Also:
* Renamed "card" to "chip" in lots of places.
* Fixed some argument ordering in `update_db`.
* Added a new function `in_mid_gameweek` to `utils.py` so we can see if we're in the middle of a gameweek.

### CODE REVIEW

**Comment by jack89roberts** [comment]
Nice, looks good to me (and massively reduces a chip run I was going to try from >2000 strategies to 57 😄). Mid-gameweek check looks good too, but I think the update DB script doesn't update the fixtures at the moment, so we may still get into trouble if fixtures are rescheduled (even if just moving kick-off times within a gameweek).

I made one remaining flake8 change, will merge to develop now.

**Comment by nbarlowATI** [comment]
I actually think flake8 is wrong here...   In an sqlalchemy filter condition, it looks like `is not` doesn't do what we want:
```
>>> from airsenal.framework.utils import *
>>> len(session.query(Fixture).all())
1520
>>> len(session.query(Fixture).filter(Fixture.result is not None).all())
1520
>>> len(session.query(Fixture).filter(Fixture.result != None).all())
1277
```
I'll put this change back, and add a `#noqa:  E711` to get flake8 to ignore that line...

**Comment by jack89roberts** [comment]
Oh right, good spot. It's likely I changed that somewhere else so I'll have a look over sqlalchemy queries at some point.

**Comment by jack89roberts** [comment]
I can't find it used in any other queries so we should be safe.

**Pull request merged**
