### PR TITLE
add notebook and stan code for dynamic model

### PR DESCRIPTION
**Pull request by anguswilliams91**
I spent a bit of time today thinking about how to generalise the team level model to account for "form" (i.e., let the team abilities become a function of time). I basically just infer an ability per team, per gameweek and put a random walk prior on it. The model takes a little longer to fit than the standard BPL one, but the HMC diagnostics were all fine after I switched to a non-centered parameterisation. I did a quick check and it didn't look like there was much variation in the parameters across time. I need to think about whether this could be improved with a better prior than a random walk.

### CODE REVIEW

**Comment by jack89roberts** [comment]
Hi @anguswilliams91 , I've had the notebook running in the background today and each chain seems to be taking increasingly long to run - 8 mins, 17 mins, 68 mins, and 4th chain is just getting started. Is that similar to how long it was taking for you or is something weird happening for me? Thanks!

**Comment by anguswilliams91** [comment]
That is a *lot* slower than it was taking on my laptop! It took 10 mins total. Are you parallelising? You can also try dropping the `control` kwarg ive set and just use the default.

**Comment by anguswilliams91** [comment]
I was being a bit lazy about prior scales before, so I've pushed a change with those hopefully improved. This should help sampling a bit, I think. Let me know how you get on if you get a chance to run it again.

**Comment by jack89roberts** [comment]
Yeah I was just doing it single core before, with `n_jobs = 4` and the changes you made it takes about 10-15 mins for me now. I have seen a couple of occasions where something seemed to go wrong (or at least different) with the fit, though, giving results like [this](https://i.imgur.com/HXNwOML.png).

That might have only been when I played with the [more experimental multithreading stuff](https://pystan.readthedocs.io/en/latest/threading_support.html).

**Comment by saba83rish** [comment]
Do you have some documentation to setup the notebook locally? I would like to play with the model based on Form from the FPL API or some other variables you might be interested and dont have time to look in for.

**Comment by nbarlowATI** [comment]
Hi @saba83rish  the notebook should basically work in the standard AIrsenal setup, from following the instructions on the main README (i.e. check you have gcc installed, create a conda environment, and do `pip install .` from the main AIrsenal directory).
Then you can populate the database by doing
```
airsenal_setup_initial_db
``` 
which should fill it with the data needed for the notebook.

Having said that, I did just have a go and there were a couple of minor issues with the setup/notebook (seaborn not in requirements.txt, and the 2016/2017 data not being loaded into the database by default though the notebook assumes it is), which I hopefully fixed in the `develop` branch.   This will be merged into `master` soon, but let us know if you get a chance to try it out, and have any success or problems! :)

**Comment by saba83rish** [comment]
@nbarlowATI i was able to get it up and running in my pycharm to run commands, but for looking at model in notebook i opened the .pynb fils in my local notebook environment. Is there a specific version of jupyter notebook i should use?

**Comment by nbarlowATI** [comment]
@saba83rish  I don't know of any reason why you'd need a specific version of jupyter notebook - I'm using 6.0.3, but haven't tried others.  What problems are you seeing with running `dynamic_model.ipynb` in your notebook environment?

**Comment by saba83rish** [comment]
image

**Comment by nbarlowATI** [comment]
Hi @saba83rish  are you running ```jupyter notebook``` from the same conda environment where you've installed airsenal?
Can you run `python` then
```
>>>from airsenal.framework.utils import *
```
from the same command line where you're launching ```jupyter notebook``` from?

**Comment by saba83rish** [comment]
image
Ah, that was it. Now past that.

**Comment by saba83rish** [comment]
image
The session.query(Result).all() is returning empty, what am I doing wrong here?

**Comment by saba83rish** [comment]
`RuntimeError: Exception: []: accessing element out of range. index 114 out of range; expecting index to be between 1 and 76; index position = 2a  (in 'dynamic_model.stan' at line 41)`

**Comment by nbarlowATI** [comment]
Hi @saba83rish  this is because by default we're only loading the past 3 seasons data into the DB, so now we're into the "2021" season, it no longer loads the "1617" season, so the assumptions in this notebook about how many rows there will be in the DataFrame don't hold.
In the `develop` branch I got round this just by ignoring the "1617" season, and changing 114 to 76 in a couple of places (as every team played 76 matches in the "1718" and "1819" seasons.   
Alternatively, you could make it load the "1617" season by changing 
```
for season in get_past_seasons(3):
```
to 
```
for season in get_past_seasons(4):
```
 in `fill_result_table.py` then redoing 
```
pip install .
airsenal_setup_initial_db
```
and then the notebook should work as is...

**Comment by saba83rish** [comment]
@nbarlowATI  Thanks its went past that, I am trying to bring in player form also into contention in the ML. 
Getting stuck here 🔢 Zero Division Error on prediction utils file where the Bayesian calculation logic exists.
As you see here I have tried to handle the exception but its still failing.
Did you guys face this?
image

**Comment by jack89roberts** [comment]
@saba83rish Have you modified the `get_player_model` or `fit_player_data` functions in any way? If not my best guess would be that this is a database issue (e.g. it gets deleted sometimes as we put it in a temporary directory). Could you check whether you get the same error after recreating the database? (`rm /tmp/data.db` followed by `airsenal_setup_initial_db`).

**Pull request merged**
