### PR TITLE
[Ready for review] Added option to run chips from the pipeline

### PR DESCRIPTION
**Pull request by subash774**
Added the following options to pipeline:
```
  --wildcard_week WILDCARD_WEEK
                        
  --free_hit_week FREE_HIT_WEEK
                       If set to 0, consider playing wildcard in any gameweeks. If set to a specific gameweek, it'll be played for that particular gameweek.
  --triple_captain_week TRIPLE_CAPTAIN_WEEK
                        play triple captain in the specified week. Choose 0 for 'any week'.
  --bench_boost_week BENCH_BOOST_WEEK
                        play bench_boost in the specified week. Choose 0 for 'any week'.
```

### CODE REVIEW

**Comment by jack89roberts** [comment]
Thanks @subash774, looks good! I'll take a proper look and get it merged to our develop branch later this week.

**Comment by jack89roberts** [comment]
Thanks again for your contribution @subash774  - I've checked it out and all working for me, will merge it to develop now and from there will be merged to the main AIrsenal branch in our next release.

**Comment by subash774** [comment]
Thanks! Please let me know if there's anything else I can help with.

**Comment by jack89roberts** [comment]
Sure any contributions are welcome! We try to label appropriate issues with `good first issue` and/or `help wanted` where appropriate, but these are a bit out of date currently (but feel free to have a look at anything). #416 and #222 (which is a one-liner) might be a couple of good candidates.

**Pull request merged**
