### PR TITLE
Add scraper for understat.com (Fixes #430)

### LINKED ISSUE #430: Find a way of getting data on when players were subbed on/off, and when goals were scored
Currently from the FPL API we have no way of knowing:
* At what minute each goal was scored
* If a player plays < 90 mins, did they start and get subbed off, or get subbed on?  (Or get subbed on and then subbed off, in a few cases!)

This means that we don't know whether a player was on the pitch when a goal was scored, which would be useful information for evaluating their defensive strength.

Is there some other API we could get this from?  (maybe https://www.football-data.org/ or similar?)
Or scrape from match reports?

### PR DESCRIPTION
**Pull request by chahak13**
This commit adds a scraper `scrape_understat.py` that aims to
scrape the goal time and goal scorer for each match from the
'15-'16 season. It also pulls in the substitution information.

### CODE REVIEW

**Comment by chahak13** [comment]
@jack89roberts I've added a scraper in the `scraper/` directory and the data files are named `goals_subs_data_{season}.json` in the `data/` directory. Let me know if this looks good or if any other changes are to be made!

**Comment by chahak13** [comment]
@jack89roberts the `black` is using 88 characters limit, right? If so, things look good on my local setup. Should hopefully work now. All except one change are majorly formatting things to confirm to `black`. Sorry for the mess :/

**Comment by chahak13** [comment]
@jack89roberts Are the tests in the dev branch not passing? Because the pytest error is not in any file that I changed.

**Comment by chahak13** [comment]
@jack89roberts That should take care of it. I was using a single `find` command instead of `find_all`. I've updated that. Let me know if it looks okay now or if there are any other changes. I've also added the data files with the new sub info added.

**Comment by jack89roberts** [comment]
That's great, I'll merge it to develop now. Thanks again @chahak13 !

**Pull request merged**
