### PR TITLE
[#209] Added CURRENT_SEASON from framework.utils to fixtures.py and test_team.py 

### PR DESCRIPTION
**Pull request by pratyushpal**
Added the 'quick fix' as proposed in the #209 by changing the value of season in fixtures.py and the value of TEST_SEASON to the global constant CURRENT_SEASON!

### CODE REVIEW

**Comment by pratyushpal** [comment]
Hey @jack89roberts! My Travis CI tests are failing because the scripts are unable to fetch the API_KEY, TEAM_ID and LEAGUE_ID from the repository settings. Is there something additional that I have to do outside of setting the constants in filenames as you described in the readme?

**Comment by jack89roberts** [comment]
Hi @pratyushpal , we have a FPL_TEAM_ID set in our Travis settings (as a "secret", though it doesn't really need to be secret!) I suspect this is failing because you don't have access to those "secrets". But Travis has been behaving a bit strangely in general recently.

If you have `pytest` installed (in your `airsenalenv` environment) you can check whether the tests pass locally by just running `pytest` from the `AIrsenal` directory. The changes look good to me though so I will merge them to develop and hopefully the Travis tests will pass there.  Thanks!

**Comment by pratyushpal** [comment]
They pass locally for me! I uploaded some secret keys on my fork. Hopefully, that fixes it!

**Comment by jack89roberts** [comment]
You can see they've passed when being run from the develop branch now 🙂 : https://travis-ci.org/github/alan-turing-institute/AIrsenal/builds/729877209

**Comment by pratyushpal** [comment]
Awesome! Thanks for that. Can I feel free to pick up any task that hasn't been taken up yet? Or is there something that you think needs immediate attention?

**Comment by jack89roberts** [comment]
Yes, feel free to pick up anything! Maybe let us know before in case someone is already working on it (and so we can help explain what the issue is/any ideas we have for how to solve it). I don't think there's anything in particular that needs immediate attention, just choose whatever you're interested in doing. We try to give the "good first issue" label to issues we think should be accessible for newcomers, so they may be a good place to start.

**Pull request merged**
