### PR TITLE
[WIP] Issue 382 - Rework entire CLI

### PR DESCRIPTION
**Pull request by chahak13**
This is a WIP PR for #382.

### CODE REVIEW

**Comment by chahak13** [comment]
@jack89roberts Can you take a look at this? The current interface lies under `airsenal/cli` directory and works under the `airsenal_cli` umbrella. If everything looks good, then I'll move it to `airsenal` and change `setup.py` accordingly. I've tried to build the interface on the existing code itself, so there isn't a lot of major change in the scripts section except for a few bookkeeping changes to accommodate the newer interface. Let me know what you think.

**Comment by jack89roberts** [comment]
- Running `airsenal_cli database` quits without doing anything or printing a message. Can we make it print the help message/something helpful (this probably applies to other commands too)?
- `airsenal_cli setup` and `airsenal_cli update` return an error about missing required arguments.
- Database setup should give a useful message if a database already exists, but I see you already have a TODO for that.
- We should probably stick to either optimise or optimize throughout the codebase but that can be for a separate  issue.

**Comment by chahak13** [comment]
Thanks for the feedback, @jack89roberts. Sorry for the late reply.

> Running airsenal_cli database quits without doing anything or printing a message. Can we make it print the help message/something helpful (this applies to other incorrect commands too, e.g. airsenal optimise --num-gameweeks 1)?

I'll do this. This shouldn't be an issue.

> airsenal_cli setup and airsenal_cli update return an error about missing required arguments.

~That's weird. Seems to work on my end. I'll try to debug why that's happening.~ Found it. This came up when I added the callback arguments. Will take a look at how to change.

> I think it would be nice to have the squad and transfer optimisation separated a bit more, e.g. the long list of arguments (with many that only apply to one or the other) is a bit confusing. Would it work to have them as separate nested commands under airsenal_cli optimise (i.e. airsenal_cli optimise transfers and airsenal_cli optimise squad? And if we do that could airsenal_cli optimise also be an alias/shorthand for airsenal_cli optimise transfers (apart from in pre-season perhaps, where it would ideally default to the squad optimisation)?

Yeah, nesting them further might be a good idea. I'm not sure how to do the preseason switch though. Do we do it based on dates? Or is there an API that I can request that data from?

I'll try to get the others done too.

**Comment by jack89roberts** [comment]
We have something to do it in the pipeline script currently, see these lines:

https://github.com/alan-turing-institute/AIrsenal/blob/359ebbc2e52272fb1bedbd62a92c9e6fdb0b1981/airsenal/scripts/airsenal_run_pipeline.py#L124-L138

It checks whether the next gameweek is the first gameweek a team has been entered for. But we can also just default the CLI to running the transfer optimisation for now if that's easier.

**Pull request closed without merging**
