### PR TITLE
[Ready for review] Continuing fixing the issue regarding the `from x import *`

### PR DESCRIPTION
**Pull request by Abelarm**
Issue #276 

- Removed all the `from x import *` from the directories:
      - **frameworks**
      -  **scraper**
      - **scripts**
- Removed all the unused imports 
- Solved calling the function with parameters which didn't exist

To check for the mantainers: 
**frameworks**
- [x] `api_utils.py` (lines 272, 288) 
- [x] `optimization_utils.py` (lines 648, 666)
- [x] `utils.py`(lines 670, 688, 692) 
- [x] `utils.py` in line 143 the  there is one kind of circular import with the import `from airsenal.framework.bpl_interface import get_fitted_team_model` the module bpl_interface needs the global variable `CURRENT_TEAMS` which is create in the previous line (142) so if we move the import to the top everything broke... need to find a solution for this:
*FIXED* with last commit moving CURRENT_SEASON and CURRENT_TEAMS into a new file called season.py

**scrape**
- [x] `scrape_fpl_archive.py` (lines 207) 

**script**
- [x] `parallel_fill_transfersuggestions_table.py` in line 34 there a call to a function `strategy_involves_2_or_more_transfers_in_gw` for which I don't find the reference in the project,  how can we solve it?
*FIXED* deleted file `parallel_fill_transfersuggestions_table.py`

### CODE REVIEW

**Comment by nbarlowATI** [comment]
Hi @Abelarm great, many thanks - this is looking good!
For the circular import problem, one solution could be to move the `get_current_season` function and the `CURRENT_SEASON` global variable into a new module `airsenal/framework/season.py`, and import from that into both `utils.py` and `bpl_interface.py` ? 

For `parallel_fill_transfersuggestion_table.py` - we can (and should) just remove that file - it was a work-in-progress for what then ended up in the regular `fill_transfersuggestion_table.py`.

If you're happy to make these changes as part of this PR that would be great!  Otherwise we can just merge this PR and make the changes in `develop`.

Thanks again!!

**Comment by Abelarm** [comment]
@nbarlowATI I'll fix the problems you pointed out and commit to this PR.

**Comment by Abelarm** [comment]
@nbarlowATI done it! :+1:

**Comment by nbarlowATI** [comment]
Awesome - many thanks @Abelarm !! :)

**Pull request merged**
