### PR TITLE
[Ready for review] Fix Issue #457

### LINKED ISSUE #457: Ensure consistent argument names across airsenal functions
E.g. gameweek vs. gw in these two:

```
airsenal_run_prediction --season 1920 --gameweek_start 1 --gameweek_end 4
airsenal_run_optimization --season 1920 --gw_start 2 --gw_end 3
```

### PR DESCRIPTION
**Pull request by chahak13**
This resolves #457. I also checked other functions to see if there were any other inconsistencies but did not see any. Let me know if these changes look good or if I should change anything.

### CODE REVIEW

**Comment by jack89roberts** [comment]
Thanks @chahak13 ! For these changes to work as intended you'll also need to replace all `args.gw_start` and `args.gw_end` with `args.gameweek_start` and `args.gameweek_end` - would you be able to make those changes too?

**Comment by chahak13** [comment]
Right, sorry. I'm not sure why I missed that.

**Comment by chahak13** [comment]
@jack89roberts Done. I think I covered the changes.

**Comment by jack89roberts** [comment]
Great, thanks! 🎉

**Pull request merged**
