### PR TITLE
Feature/266 multiple team ids

### PR DESCRIPTION
**Pull request by nbarlowATI**
This extends the work in #322 which addressed Issue #255, and also covers #256, adding a `fpl_team_id` column to the Transaction table in the database, and adding `fpl_team_id` as an argument to multiple functions in `transaction_utils.py`, `optimization_utils.py`, `fill_transaction_table.py` and `update_db.py` such that multiple FPL squads can be stored in the database.

This is a necessary precursor to the "replay-season-optimization", hopefully coming soon :)

### CODE REVIEW

**Comment by jack89roberts** [comment]
Cool, nice work @nbarlowATI ! I guess we should merge this one after #322 is done?

**Comment by nbarlowATI** [comment]
Everything in #322 is incorporated into this, so I think it's safe to either merge #322 then merge this, or just directly merge this.

**Comment by jack89roberts** [comment]
Started to have a quick look and I think `airsenal_run_pipeline` doesn't work without explicitly setting the team ID at the moment. I haven't checked fully but from what I can tell the functions like the one below end up setting the team ID as the string "None", rather than it being interpreted as `None` and loading it from the env variable/file as normal:

https://github.com/alan-turing-institute/AIrsenal/blob/d0c9a40fc2574dd9671a43d62e5cb43b97549e73/airsenal/scripts/airsenal_run_pipeline.py#L79-L83

**Comment by nbarlowATI** [comment]
Ah, cool, thanks for checking!  Yep, I hadn't tried running the `airsenal_run_pipeline`, just the `airsenal_setup_initial_db` and `airsenal_update_db` individually... I'll look into that, and also apply a maximum gw of NEXT_GAMEWEEK for the finding the initial team...

**Pull request merged**
